name: deep_learning
channels:
  - simpleitk
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1=main
  - blas=1.0=mkl
  - brotlipy=0.7.0=py38h8df0ef7_1001
  - bzip2=1.0.8=h516909a_3
  - ca-certificates=2020.12.5=ha878542_0
  - cairo=1.16.0=h3fc0475_1005
  - certifi=2020.12.5=py38h578d9bd_1
  - cffi=1.14.4=py38ha312104_0
  - chardet=3.0.4=py38h924ce5b_1008
  - cloudpickle=1.6.0=py_0
  - cryptography=3.2.1=py38h7699a38_0
  - cudatoolkit=10.2.89=hfd86e86_1
  - cycler=0.10.0=py38_0
  - cytoolz=0.11.0=py38h7b6447c_0
  - dask-core=2.30.0=py_0
  - dbus=1.13.18=hb2f20db_0
  - decorator=4.4.2=py_0
  - dominate=2.4.0=py_0
  - et_xmlfile=1.0.1=py_1001
  - expat=2.2.10=he6710b0_2
  - ffmpeg=4.3.1=h3215721_1
  - fontconfig=2.13.1=h6c09931_0
  - freetype=2.10.4=h5ab3b9f_0
  - geos=3.8.1=he1b5a44_0
  - gettext=0.19.8.1=hf34092f_1004
  - glib=2.66.1=h680cd38_0
  - gmp=6.2.1=h58526e2_0
  - gnutls=3.6.13=h85f3911_1
  - graphite2=1.3.13=h58526e2_1001
  - gst-plugins-base=1.14.5=h0935bb2_2
  - gstreamer=1.14.5=h36ae1b5_2
  - harfbuzz=2.7.2=hee91db6_0
  - hdf5=1.10.6=nompi_h3c11f04_101
  - icu=67.1=he1b5a44_0
  - idna=2.10=pyh9f0ad1d_0
  - imageio=2.9.0=py_0
  - imgaug=0.4.0=py_1
  - intel-openmp=2020.2=254
  - jasper=1.900.1=h07fcdf6_1006
  - jdcal=1.4.1=py_0
  - jpeg=9d=h36c2ea0_0
  - jsonpatch=1.24=py_0
  - jsonpointer=2.0=py_0
  - kiwisolver=1.3.0=py38h2531618_0
  - krb5=1.17.2=h926e7f8_0
  - lame=3.100=h14c3975_1001
  - lcms2=2.11=h396b838_0
  - ld_impl_linux-64=2.33.1=h53a641e_7
  - libblas=3.9.0=1_h6e990d7_netlib
  - libcblas=3.9.0=3_h893e4fe_netlib
  - libclang=10.0.1=default_hde54327_1
  - libedit=3.1.20191231=h14c3975_1
  - libevent=2.1.10=hcdb4288_3
  - libffi=3.2.1=he1b5a44_1007
  - libgcc-ng=9.1.0=hdf63c60_0
  - libgfortran-ng=7.5.0=hae1eefd_17
  - libgfortran4=7.5.0=hae1eefd_17
  - libiconv=1.16=h516909a_0
  - liblapack=3.9.0=3_h893e4fe_netlib
  - liblapacke=3.9.0=3_h893e4fe_netlib
  - libllvm10=10.0.1=he513fc3_3
  - libopencv=4.5.0=py38_3
  - libpng=1.6.37=hbc83047_0
  - libpq=12.3=h255efa7_3
  - libsodium=1.0.18=h36c2ea0_1
  - libstdcxx-ng=9.1.0=hdf63c60_0
  - libtiff=4.1.0=h2733197_1
  - libuuid=1.0.3=h1bed415_2
  - libwebp-base=1.1.0=h36c2ea0_3
  - libxcb=1.14=h7b6447c_0
  - libxkbcommon=0.10.0=he1b5a44_0
  - libxml2=2.9.10=h68273f3_2
  - lz4-c=1.9.2=heb0550a_3
  - matplotlib=3.3.2=0
  - matplotlib-base=3.3.2=py38h817c723_0
  - mkl=2020.2=256
  - mkl-service=2.3.0=py38he904b0f_0
  - mkl_fft=1.2.0=py38h23d657b_0
  - mkl_random=1.1.1=py38h0573a6f_0
  - mysql-common=8.0.21=2
  - mysql-libs=8.0.21=hf3661c5_2
  - ncurses=6.2=he6710b0_1
  - nettle=3.6=he412f7d_0
  - networkx=2.5=py_0
  - ninja=1.10.1=py38hfd86e86_0
  - nspr=4.29=he1b5a44_1
  - nss=3.59=h2c00c37_0
  - numpy=1.19.2=py38h54aff64_0
  - numpy-base=1.19.2=py38hfa32c7d_0
  - olefile=0.46=py_0
  - opencv=4.5.0=py38_3
  - openh264=2.1.1=h8b12597_0
  - openpyxl=3.0.6=pyhd3eb1b0_0
  - openssl=1.1.1k=h27cfd23_0
  - pandas=1.2.2=py38ha9443f7_0
  - pcre=8.44=he6710b0_0
  - pillow=8.0.1=py38he98fc37_0
  - pixman=0.38.0=h516909a_1003
  - py-opencv=4.5.0=py38h81c977d_3
  - pycparser=2.20=pyh9f0ad1d_2
  - pydicom=2.1.2=pyhd3deb0d_0
  - pyopenssl=19.1.0=py_1
  - pyparsing=2.4.7=py_0
  - pyqt=5.12.3=py38ha8c2ead_4
  - pysocks=1.7.1=py38h924ce5b_2
  - python=3.8.3=cpython_he5300dc_0
  - python-dateutil=2.8.1=py_0
  - python_abi=3.8=1_cp38
  - pytorch=1.6.0=py3.8_cuda10.2.89_cudnn7.6.5_0
  - pytz=2021.1=pyhd3eb1b0_0
  - pywavelets=1.1.1=py38h7b6447c_2
  - pyyaml=5.3.1=py38h7b6447c_1
  - pyzmq=20.0.0=py38h1d1b12f_1
  - qt=5.12.9=h1f2b2cb_0
  - readline=8.0=h7b6447c_0
  - requests=2.25.0=pyhd3deb0d_0
  - scikit-image=0.17.2=py38hdf5156a_0
  - scipy=1.5.2=py38h0b6359f_0
  - shapely=1.7.1=py38h2765ab7_1
  - simpleitk=2.0.1=py38hf484d3e_0
  - sip=4.19.13=py38he6710b0_0
  - six=1.15.0=py38h06a4308_0
  - sqlite=3.33.0=h62c20be_0
  - tifffile=2020.10.1=py38hdd07704_2
  - tk=8.6.10=hbc83047_0
  - toolz=0.11.1=py_0
  - torchfile=0.1.0=py_0
  - torchvision=0.7.0=py38_cu102
  - tornado=6.1=py38h25fe258_0
  - urllib3=1.25.11=py_0
  - visdom=0.1.8.9=0
  - websocket-client=0.57.0=py38h32f6830_3
  - wheel=0.35.1=pyhd3eb1b0_0
  - x264=1!152.20180806=h14c3975_0
  - xorg-kbproto=1.0.7=h14c3975_1002
  - xorg-libice=1.0.10=h516909a_0
  - xorg-libsm=1.2.2=h470a237_5
  - xorg-libx11=1.6.12=h516909a_0
  - xorg-libxext=1.3.4=h516909a_0
  - xorg-libxrender=0.9.10=h516909a_1002
  - xorg-renderproto=0.11.1=h14c3975_1002
  - xorg-xextproto=7.3.0=h14c3975_1002
  - xorg-xproto=7.0.31=h14c3975_1007
  - xz=5.2.5=h7b6447c_0
  - yaml=0.2.5=h7b6447c_0
  - zeromq=4.3.3=h58526e2_3
  - zlib=1.2.11=h7b6447c_3
  - zstd=1.4.5=h9ceee32_0
  - pip:
    - dicompyler==0.5.0
    - medpy==0.4.0
    - pip==21.0.1
    - pynrrd==0.4.2
    - pyqt5-sip==4.19.18
    - pyqtchart==5.12
    - pyqtwebengine==5.12.1
    - setuptools==54.2.0
prefix: /home/ndahiya/anaconda3/envs/deep_learning
